import type { UserWithRolesRead } from '@/services/access'

export const PERMISSIONS = {
  userRead: 'user_read',
  userCreate: 'user_create',
  userDelete: 'user_delete',
  userAssignRoles: 'user_assign_roles',
  roleRead: 'role_read',
  roleCreate: 'role_create',
  roleUpdate: 'role_update',
  roleDelete: 'role_delete',
  roleAssignPermissions: 'role_assign_permissions',
  permissionRead: 'permission_read',
  permissionCreate: 'permission_create',
  permissionUpdate: 'permission_update',
  permissionDelete: 'permission_delete',
  providerRead: 'provider_read',
  providerCreate: 'provider_create',
  providerUpdate: 'provider_update',
  providerDelete: 'provider_delete',
  providerTest: 'provider_test',
  modelRead: 'model_read',
  modelCreate: 'model_create',
  modelUpdate: 'model_update',
  modelDelete: 'model_delete',
  promptRead: 'prompt_read',
  promptCreate: 'prompt_create',
  promptUpdate: 'prompt_update',
  promptDelete: 'prompt_delete',
  promptPublish: 'prompt_publish',
  agentRead: 'agent_read',
  agentCreate: 'agent_create',
  agentUpdate: 'agent_update',
  agentDelete: 'agent_delete',
  agentPublish: 'agent_publish',
  agentStartStop: 'agent_start_stop',
  knowledgeRead: 'knowledge_read',
  knowledgeCreate: 'knowledge_create',
  knowledgeUpdate: 'knowledge_update',
  knowledgeDelete: 'knowledge_delete',
  knowledgeDocumentManage: 'knowledge_document_manage',
  knowledgeSegmentUpdate: 'knowledge_segment_update',
  knowledgeRetrieve: 'knowledge_retrieve',
  toolRead: 'tool_read',
  toolCreate: 'tool_create',
  toolUpdate: 'tool_update',
  toolDelete: 'tool_delete',
  toolEnable: 'tool_enable',
  toolTest: 'tool_test',
  conversationRead: 'conversation_read',
  conversationCreate: 'conversation_create',
  conversationUpdate: 'conversation_update',
  conversationDelete: 'conversation_delete',
  conversationExport: 'conversation_export',
  conversationAnnotate: 'conversation_annotate',
  analyticsRead: 'analytics_read',
  analyticsExport: 'analytics_export',
  apiKeyRead: 'api_key_read',
  apiKeyCreate: 'api_key_create',
  apiKeyUpdate: 'api_key_update',
  apiKeyDelete: 'api_key_delete',
  auditRead: 'audit_read',
  alertRead: 'alert_read',
  alertCreate: 'alert_create',
  alertUpdate: 'alert_update',
  alertDelete: 'alert_delete',
  alertHandle: 'alert_handle',
  settingsRead: 'settings_read',
  settingsUpdate: 'settings_update',
  dashboardRead: 'dashboard_read',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export function hasPermission(user: UserWithRolesRead | null, permission: PermissionCode): boolean {
  if (!user) return false
  if (user.is_superuser) return true
  return user.roles.some((role) =>
    role.permissions.some((assignedPermission) => assignedPermission.code === permission),
  )
}
