"""system_management_dashboard

Revision ID: 1ef7a711510b
Revises: ac8541d68b17
Create Date: 2026-07-19 20:10:09.655236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef7a711510b'
down_revision: Union[str, Sequence[str], None] = 'ac8541d68b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=150), nullable=False, comment='规则名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='规则描述'),
    sa.Column('condition', sa.JSON(), nullable=False, comment='规则条件'),
    sa.Column('notifications', sa.JSON(), nullable=False, comment='通知渠道'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='规则状态'),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=True)
    op.create_index(op.f('ix_alert_rules_status'), 'alert_rules', ['status'], unique=False)
    op.create_table('api_access_keys',
    sa.Column('name', sa.String(length=150), nullable=False, comment='API Key 名称'),
    sa.Column('key_prefix', sa.String(length=20), nullable=False, comment='Key 前缀'),
    sa.Column('key_suffix', sa.String(length=10), nullable=False, comment='Key 尾部'),
    sa.Column('secret_hash', sa.String(length=64), nullable=False, comment='Key 哈希'),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='权限码'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='每分钟限额'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_index(op.f('ix_api_access_keys_created_by_id'), 'api_access_keys', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_api_access_keys_expires_at'), 'api_access_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_access_keys_key_prefix'), 'api_access_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_access_keys_name'), 'api_access_keys', ['name'], unique=True)
    op.create_index(op.f('ix_api_access_keys_status'), 'api_access_keys', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户 ID'),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment='用户名快照'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作'),
    sa.Column('resource', sa.String(length=100), nullable=False, comment='资源类型'),
    sa.Column('resource_name', sa.String(length=500), nullable=False, comment='资源路径'),
    sa.Column('details', sa.JSON(), nullable=False, comment='非敏感详情'),
    sa.Column('ip_address', sa.String(length=100), nullable=True, comment='来源 IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='结果'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='发生时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_name'), 'audit_logs', ['user_name'], unique=False)
    op.create_table('system_alerts',
    sa.Column('type', sa.String(length=20), nullable=False, comment='告警类型'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('message', sa.String(length=1000), nullable=False, comment='消息'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='来源'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='严重级别'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态'),
    sa.Column('count', sa.Integer(), nullable=False, comment='发生次数'),
    sa.Column('first_occurred_at', sa.DateTime(), nullable=False, comment='首次发生'),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=False, comment='最近发生'),
    sa.Column('acknowledged_by_id', sa.BigInteger(), nullable=True, comment='确认人 ID'),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True, comment='确认时间'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='解决时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_alerts_last_occurred_at'), 'system_alerts', ['last_occurred_at'], unique=False)
    op.create_index(op.f('ix_system_alerts_severity'), 'system_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_system_alerts_source'), 'system_alerts', ['source'], unique=False)
    op.create_index(op.f('ix_system_alerts_status'), 'system_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_system_alerts_type'), 'system_alerts', ['type'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_key', sa.String(length=50), nullable=False, comment='设置标识'),
    sa.Column('system_name', sa.String(length=150), nullable=False, comment='系统名称'),
    sa.Column('system_description', sa.String(length=500), nullable=False, comment='系统描述'),
    sa.Column('default_language', sa.String(length=20), nullable=False, comment='默认语言'),
    sa.Column('default_model', sa.String(length=150), nullable=False, comment='默认模型'),
    sa.Column('default_temperature', sa.Float(), nullable=False, comment='默认 Temperature'),
    sa.Column('default_max_tokens', sa.Integer(), nullable=False, comment='默认最大 Token'),
    sa.Column('smtp_server', sa.String(length=255), nullable=False, comment='SMTP 服务器'),
    sa.Column('smtp_port', sa.Integer(), nullable=False, comment='SMTP 端口'),
    sa.Column('sender_email', sa.String(length=255), nullable=False, comment='发件人邮箱'),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True, comment='更新人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    system_settings = sa.table(
        'system_settings',
        sa.column('setting_key', sa.String()), sa.column('system_name', sa.String()),
        sa.column('system_description', sa.String()), sa.column('default_language', sa.String()),
        sa.column('default_model', sa.String()), sa.column('default_temperature', sa.Float()),
        sa.column('default_max_tokens', sa.Integer()), sa.column('smtp_server', sa.String()),
        sa.column('smtp_port', sa.Integer()), sa.column('sender_email', sa.String()),
    )
    op.bulk_insert(system_settings, [{
        'setting_key': 'main', 'system_name': '辰光 Agent',
        'system_description': '企业智能 Agent 管理平台', 'default_language': 'zh-CN',
        'default_model': '', 'default_temperature': 0.7, 'default_max_tokens': 4096,
        'smtp_server': '', 'smtp_port': 587, 'sender_email': '',
    }])
    permissions = sa.table(
        'permissions', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()),
        sa.column('name', sa.String()), sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()))
    role_permissions = sa.table(
        'role_permissions', sa.column('role_id', sa.BigInteger()), sa.column('permission_id', sa.BigInteger()),
    )
    catalog = (
        ('api_key_read', '查看 API Key', '查看 API Key 元数据'),
        ('api_key_create', '创建 API Key', '签发 API Key'),
        ('api_key_update', '更新 API Key', '修改或轮换 API Key'),
        ('api_key_delete', '删除 API Key', '撤销并删除 API Key'),
        ('audit_read', '查看审计日志', '查看平台操作审计'),
        ('alert_read', '查看告警', '查看告警和规则'),
        ('alert_create', '创建告警', '创建告警事件和规则'),
        ('alert_update', '更新告警', '修改告警事件和规则'),
        ('alert_delete', '删除告警', '删除告警事件和规则'),
        ('alert_handle', '处理告警', '确认或解决告警'),
        ('settings_read', '查看系统设置', '查看平台系统设置'),
        ('settings_update', '更新系统设置', '修改平台系统设置'),
        ('dashboard_read', '查看工作台', '查看平台真实汇总数据'),
    )
    connection = op.get_bind()
    existing_codes = set(connection.execute(sa.select(permissions.c.code)).scalars())
    missing = [{'code': code, 'name': name, 'description': description} for code, name, description in catalog if code not in existing_codes]
    if missing: op.bulk_insert(permissions, missing)
    admin_role_id = connection.execute(sa.select(roles.c.id).where(roles.c.code == 'admin')).scalar_one_or_none()
    if admin_role_id is not None:
        permission_ids = list(connection.execute(sa.select(permissions.c.id).where(permissions.c.code.in_([code for code, _, _ in catalog]))).scalars())
        existing_assignments = set(connection.execute(sa.select(role_permissions.c.permission_id).where(role_permissions.c.role_id == admin_role_id)).scalars())
        assignments = [{'role_id': admin_role_id, 'permission_id': pid} for pid in permission_ids if pid not in existing_assignments]
        if assignments: op.bulk_insert(role_permissions, assignments)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_alerts_type'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_status'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_source'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_severity'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_last_occurred_at'), table_name='system_alerts')
    op.drop_table('system_alerts')
    op.drop_index(op.f('ix_audit_logs_user_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_access_keys_status'), table_name='api_access_keys')
    op.drop_index(op.f('ix_api_access_keys_name'), table_name='api_access_keys')
    op.drop_index(op.f('ix_api_access_keys_key_prefix'), table_name='api_access_keys')
    op.drop_index(op.f('ix_api_access_keys_expires_at'), table_name='api_access_keys')
    op.drop_index(op.f('ix_api_access_keys_created_by_id'), table_name='api_access_keys')
    op.drop_table('api_access_keys')
    op.drop_index(op.f('ix_alert_rules_status'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    op.drop_table('alert_rules')
    permission_codes = (
        'api_key_read', 'api_key_create', 'api_key_update', 'api_key_delete', 'audit_read',
        'alert_read', 'alert_create', 'alert_update', 'alert_delete', 'alert_handle',
        'settings_read', 'settings_update', 'dashboard_read',
    )
    op.execute(sa.text('DELETE FROM permissions WHERE code IN :codes').bindparams(
        sa.bindparam('codes', expanding=True, value=permission_codes)
    ))
    # ### end Alembic commands ###
