"""resource_management_core

Revision ID: 829d7f3aeaf8
Revises: 66b777046b3a
Create Date: 2026-07-19 19:24:00.531454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829d7f3aeaf8'
down_revision: Union[str, Sequence[str], None] = '66b777046b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_providers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='供应商名称'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='供应商类型'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='连接状态'),
    sa.Column('endpoint', sa.String(length=500), nullable=False, comment='API 端点'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True, comment='加密后的 API Key'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='供应商描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_providers_name'), 'model_providers', ['name'], unique=True)
    op.create_index(op.f('ix_model_providers_status'), 'model_providers', ['status'], unique=False)
    op.create_index(op.f('ix_model_providers_type'), 'model_providers', ['type'], unique=False)
    op.create_table('models',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型显示名称'),
    sa.Column('model_id', sa.String(length=150), nullable=False, comment='供应商模型标识'),
    sa.Column('provider_id', sa.BigInteger(), nullable=False, comment='供应商 ID'),
    sa.Column('capabilities', sa.JSON(), nullable=False, comment='模型能力'),
    sa.Column('context_length', sa.Integer(), nullable=False, comment='上下文长度'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='模型状态'),
    sa.Column('input_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='输入价格'),
    sa.Column('output_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='输出价格'),
    sa.Column('currency', sa.String(length=20), nullable=False, comment='计价单位'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认模型'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_models_provider_model_id')
    )
    op.create_index(op.f('ix_models_is_default'), 'models', ['is_default'], unique=False)
    op.create_index(op.f('ix_models_model_id'), 'models', ['model_id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_models_status'), 'models', ['status'], unique=False)
    op.create_table('prompts',
    sa.Column('name', sa.String(length=150), nullable=False, comment='Prompt 名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Prompt 描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Prompt 分类'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('content', sa.Text(), nullable=False, comment='Prompt 内容'),
    sa.Column('variables', sa.JSON(), nullable=False, comment='变量定义'),
    sa.Column('version', sa.String(length=30), nullable=False, comment='当前发布版本'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='发布状态'),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.create_index(op.f('ix_prompts_created_by_id'), 'prompts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=True)
    op.create_index(op.f('ix_prompts_status'), 'prompts', ['status'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('prompt_id', sa.BigInteger(), nullable=False, comment='Prompt ID'),
    sa.Column('version', sa.String(length=30), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容快照'),
    sa.Column('variables', sa.JSON(), nullable=False, comment='变量快照'),
    sa.Column('changelog', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否当前版本'),
    sa.Column('published_by_id', sa.BigInteger(), nullable=True, comment='发布人 ID'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version', name='uq_prompt_versions_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_is_current'), 'prompt_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.BigInteger()),
        sa.column('code', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()))
    role_permissions = sa.table(
        'role_permissions',
        sa.column('role_id', sa.BigInteger()),
        sa.column('permission_id', sa.BigInteger()),
    )
    catalog = (
        ('provider_read', '查看模型供应商', '查看模型供应商配置'),
        ('provider_create', '创建模型供应商', '创建模型供应商配置'),
        ('provider_update', '更新模型供应商', '修改模型供应商配置'),
        ('provider_delete', '删除模型供应商', '删除供应商及其模型'),
        ('provider_test', '测试供应商连接', '测试供应商端点和凭证'),
        ('model_read', '查看模型', '查看模型配置'),
        ('model_create', '创建模型', '登记模型配置'),
        ('model_update', '更新模型', '修改模型配置'),
        ('model_delete', '删除模型', '删除模型配置'),
        ('prompt_read', '查看 Prompt', '查看 Prompt 和版本'),
        ('prompt_create', '创建 Prompt', '创建 Prompt 草稿'),
        ('prompt_update', '更新 Prompt', '修改 Prompt 草稿'),
        ('prompt_delete', '删除 Prompt', '删除 Prompt 和版本'),
        ('prompt_publish', '发布 Prompt', '发布或回滚 Prompt 版本'),
    )
    connection = op.get_bind()
    existing_codes = set(connection.execute(sa.select(permissions.c.code)).scalars())
    missing = [
        {'code': code, 'name': name, 'description': description}
        for code, name, description in catalog
        if code not in existing_codes
    ]
    if missing:
        op.bulk_insert(permissions, missing)

    admin_role_id = connection.execute(
        sa.select(roles.c.id).where(roles.c.code == 'admin')
    ).scalar_one_or_none()
    if admin_role_id is not None:
        codes = [code for code, _, _ in catalog]
        permission_ids = list(connection.execute(
            sa.select(permissions.c.id).where(permissions.c.code.in_(codes))
        ).scalars())
        existing_assignments = set(connection.execute(
            sa.select(role_permissions.c.permission_id).where(role_permissions.c.role_id == admin_role_id)
        ).scalars())
        assignments = [
            {'role_id': admin_role_id, 'permission_id': permission_id}
            for permission_id in permission_ids
            if permission_id not in existing_assignments
        ]
        if assignments:
            op.bulk_insert(role_permissions, assignments)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_is_current'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_prompts_status'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_created_by_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_models_status'), table_name='models')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_model_id'), table_name='models')
    op.drop_index(op.f('ix_models_is_default'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_model_providers_type'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_status'), table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_name'), table_name='model_providers')
    op.drop_table('model_providers')
    permission_codes = (
        'provider_read', 'provider_create', 'provider_update', 'provider_delete', 'provider_test',
        'model_read', 'model_create', 'model_update', 'model_delete',
        'prompt_read', 'prompt_create', 'prompt_update', 'prompt_delete', 'prompt_publish',
    )
    op.execute(sa.text('DELETE FROM permissions WHERE code IN :codes').bindparams(
        sa.bindparam('codes', expanding=True, value=permission_codes)
    ))
    # ### end Alembic commands ###
