"""conversation_analytics

Revision ID: ac8541d68b17
Revises: eb155c4d538b
Create Date: 2026-07-19 19:58:40.534783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8541d68b17'
down_revision: Union[str, Sequence[str], None] = 'eb155c4d538b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('agent_id', sa.BigInteger(), nullable=True, comment='Agent ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户 ID'),
    sa.Column('model_id', sa.BigInteger(), nullable=True, comment='模型 ID'),
    sa.Column('agent_name_snapshot', sa.String(length=150), nullable=False, comment='Agent 名称快照'),
    sa.Column('user_name_snapshot', sa.String(length=100), nullable=False, comment='用户名快照'),
    sa.Column('model_name_snapshot', sa.String(length=150), nullable=True, comment='模型名称快照'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='会话状态'),
    sa.Column('turn_count', sa.Integer(), nullable=False, comment='用户轮次数'),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='输入 Token'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='输出 Token'),
    sa.Column('cost', sa.Numeric(precision=18, scale=8), nullable=False, comment='已记录成本'),
    sa.Column('duration', sa.Float(), nullable=False, comment='总时长（秒）'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='会话标签'),
    sa.Column('error_message', sa.String(length=1000), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('ended_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_model_id'), 'conversations', ['model_id'], unique=False)
    op.create_index(op.f('ix_conversations_started_at'), 'conversations', ['started_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('conversation_annotations',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='会话 ID'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 1-5'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='问题标签'),
    sa.Column('notes', sa.Text(), nullable=True, comment='标注说明'),
    sa.Column('annotated_by_id', sa.BigInteger(), nullable=True, comment='标注人 ID'),
    sa.Column('annotated_at', sa.DateTime(), nullable=False, comment='标注时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['annotated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', name='uq_conversation_annotations_conversation_id')
    )
    op.create_index(op.f('ix_conversation_annotations_annotated_at'), 'conversation_annotations', ['annotated_at'], unique=False)
    op.create_index(op.f('ix_conversation_annotations_conversation_id'), 'conversation_annotations', ['conversation_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='会话 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='消息时间'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='消息 Token'),
    sa.Column('tool_calls', sa.JSON(), nullable=False, comment='工具调用记录'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_role'), 'conversation_turns', ['role'], unique=False)
    op.create_index(op.f('ix_conversation_turns_timestamp'), 'conversation_turns', ['timestamp'], unique=False)
    op.create_table('trace_steps',
    sa.Column('turn_id', sa.BigInteger(), nullable=False, comment='轮次 ID'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='步骤类型'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='步骤名称'),
    sa.Column('input_data', sa.JSON(), nullable=True, comment='步骤输入'),
    sa.Column('output_data', sa.JSON(), nullable=True, comment='步骤输出'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='耗时毫秒'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='步骤状态'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='输入 Token'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='输出 Token'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总 Token'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='步骤元数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_steps_turn_id'), 'trace_steps', ['turn_id'], unique=False)
    op.create_index(op.f('ix_trace_steps_type'), 'trace_steps', ['type'], unique=False)
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.BigInteger()),
        sa.column('code', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()))
    role_permissions = sa.table(
        'role_permissions',
        sa.column('role_id', sa.BigInteger()),
        sa.column('permission_id', sa.BigInteger()),
    )
    catalog = (
        ('conversation_read', '查看会话', '查看会话、轮次和链路'),
        ('conversation_create', '记录会话', '创建会话并写入轮次和链路'),
        ('conversation_update', '更新会话', '结束会话或更新运行结果'),
        ('conversation_delete', '删除会话', '删除会话及其完整记录'),
        ('conversation_export', '导出会话', '导出会话 JSON 或文本'),
        ('conversation_annotate', '标注会话', '新增或更新会话人工标注'),
        ('analytics_read', '查看分析', '查看真实会话聚合分析'),
        ('analytics_export', '导出分析', '导出分析 CSV 报表'),
    )
    connection = op.get_bind()
    existing_codes = set(connection.execute(sa.select(permissions.c.code)).scalars())
    missing = [
        {'code': code, 'name': name, 'description': description}
        for code, name, description in catalog
        if code not in existing_codes
    ]
    if missing:
        op.bulk_insert(permissions, missing)
    admin_role_id = connection.execute(
        sa.select(roles.c.id).where(roles.c.code == 'admin')
    ).scalar_one_or_none()
    if admin_role_id is not None:
        codes = [code for code, _, _ in catalog]
        permission_ids = list(connection.execute(
            sa.select(permissions.c.id).where(permissions.c.code.in_(codes))
        ).scalars())
        existing_assignments = set(connection.execute(
            sa.select(role_permissions.c.permission_id).where(role_permissions.c.role_id == admin_role_id)
        ).scalars())
        assignments = [
            {'role_id': admin_role_id, 'permission_id': permission_id}
            for permission_id in permission_ids
            if permission_id not in existing_assignments
        ]
        if assignments:
            op.bulk_insert(role_permissions, assignments)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_steps_type'), table_name='trace_steps')
    op.drop_index(op.f('ix_trace_steps_turn_id'), table_name='trace_steps')
    op.drop_table('trace_steps')
    op.drop_index(op.f('ix_conversation_turns_timestamp'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_role'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_conversation_annotations_conversation_id'), table_name='conversation_annotations')
    op.drop_index(op.f('ix_conversation_annotations_annotated_at'), table_name='conversation_annotations')
    op.drop_table('conversation_annotations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_started_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_model_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    permission_codes = (
        'conversation_read', 'conversation_create', 'conversation_update',
        'conversation_delete', 'conversation_export', 'conversation_annotate',
        'analytics_read', 'analytics_export',
    )
    op.execute(sa.text('DELETE FROM permissions WHERE code IN :codes').bindparams(
        sa.bindparam('codes', expanding=True, value=permission_codes)
    ))
    # ### end Alembic commands ###
