"""agent_management

Revision ID: bc34539ac5b8
Revises: 829d7f3aeaf8
Create Date: 2026-07-19 19:33:20.718009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc34539ac5b8'
down_revision: Union[str, Sequence[str], None] = '829d7f3aeaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=150), nullable=False, comment='Agent 名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Agent 描述'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='Agent 类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='运行状态'),
    sa.Column('model_id', sa.BigInteger(), nullable=True, comment='模型 ID'),
    sa.Column('config', sa.JSON(), nullable=False, comment='Agent 配置'),
    sa.Column('success_rate', sa.Numeric(precision=6, scale=2), nullable=False, comment='近 7 日成功率'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近 7 日调用量'),
    sa.Column('version', sa.String(length=30), nullable=False, comment='当前发布版本'),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_created_by_id'), 'agents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_agents_model_id'), 'agents', ['model_id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_type'), 'agents', ['type'], unique=False)
    op.create_table('agent_versions',
    sa.Column('agent_id', sa.BigInteger(), nullable=False, comment='Agent ID'),
    sa.Column('version', sa.String(length=30), nullable=False, comment='版本号'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='名称快照'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述快照'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='类型快照'),
    sa.Column('model_id', sa.BigInteger(), nullable=True, comment='模型 ID 快照'),
    sa.Column('config', sa.JSON(), nullable=False, comment='配置快照'),
    sa.Column('changelog', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否当前版本'),
    sa.Column('published_by_id', sa.BigInteger(), nullable=True, comment='发布人 ID'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_versions_agent_version')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_versions_is_current'), 'agent_versions', ['is_current'], unique=False)
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.BigInteger()),
        sa.column('code', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()))
    role_permissions = sa.table(
        'role_permissions',
        sa.column('role_id', sa.BigInteger()),
        sa.column('permission_id', sa.BigInteger()),
    )
    catalog = (
        ('agent_read', '查看 Agent', '查看 Agent 配置和版本'),
        ('agent_create', '创建 Agent', '创建 Agent 草稿'),
        ('agent_update', '更新 Agent', '修改 Agent 配置'),
        ('agent_delete', '删除 Agent', '删除 Agent 和版本'),
        ('agent_publish', '发布 Agent', '发布或回滚 Agent 版本'),
        ('agent_start_stop', '启停 Agent', '启动或停止已发布 Agent'),
    )
    connection = op.get_bind()
    existing_codes = set(connection.execute(sa.select(permissions.c.code)).scalars())
    missing = [
        {'code': code, 'name': name, 'description': description}
        for code, name, description in catalog
        if code not in existing_codes
    ]
    if missing:
        op.bulk_insert(permissions, missing)

    admin_role_id = connection.execute(
        sa.select(roles.c.id).where(roles.c.code == 'admin')
    ).scalar_one_or_none()
    if admin_role_id is not None:
        codes = [code for code, _, _ in catalog]
        permission_ids = list(connection.execute(
            sa.select(permissions.c.id).where(permissions.c.code.in_(codes))
        ).scalars())
        existing_assignments = set(connection.execute(
            sa.select(role_permissions.c.permission_id).where(role_permissions.c.role_id == admin_role_id)
        ).scalars())
        assignments = [
            {'role_id': admin_role_id, 'permission_id': permission_id}
            for permission_id in permission_ids
            if permission_id not in existing_assignments
        ]
        if assignments:
            op.bulk_insert(role_permissions, assignments)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_versions_is_current'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_agents_type'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_model_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_by_id'), table_name='agents')
    op.drop_table('agents')
    permission_codes = (
        'agent_read', 'agent_create', 'agent_update',
        'agent_delete', 'agent_publish', 'agent_start_stop',
    )
    op.execute(sa.text('DELETE FROM permissions WHERE code IN :codes').bindparams(
        sa.bindparam('codes', expanding=True, value=permission_codes)
    ))
    # ### end Alembic commands ###
