"""knowledge_management

Revision ID: c6e99bac6d31
Revises: bc34539ac5b8
Create Date: 2026-07-19 19:41:37.967641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e99bac6d31'
down_revision: Union[str, Sequence[str], None] = 'bc34539ac5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=150), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='知识库描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='知识库状态'),
    sa.Column('document_count', sa.Integer(), nullable=False, comment='文档数量'),
    sa.Column('segment_count', sa.Integer(), nullable=False, comment='分段数量'),
    sa.Column('embedding_model', sa.String(length=150), nullable=False, comment='Embedding 配置标识'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分段大小'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='分段重叠'),
    sa.Column('chunk_method', sa.String(length=20), nullable=False, comment='分段方式'),
    sa.Column('retrieval_strategy', sa.String(length=20), nullable=False, comment='检索策略'),
    sa.Column('top_k', sa.Integer(), nullable=False, comment='默认返回数量'),
    sa.Column('similarity_threshold', sa.Float(), nullable=False, comment='相关度阈值'),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_created_by_id'), 'knowledge_bases', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=True)
    op.create_index(op.f('ix_knowledge_bases_status'), 'knowledge_bases', ['status'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False, comment='知识库 ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='相对存储路径'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态'),
    sa.Column('segment_count', sa.Integer(), nullable=False, comment='分段数量'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字符/词项数量'),
    sa.Column('error_message', sa.String(length=1000), nullable=True, comment='处理错误'),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=True, comment='上传人 ID'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理完成时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_knowledge_documents_file_name'), 'knowledge_documents', ['file_name'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_uploaded_by_id'), 'knowledge_documents', ['uploaded_by_id'], unique=False)
    op.create_table('knowledge_segments',
    sa.Column('knowledge_base_id', sa.BigInteger(), nullable=False, comment='知识库 ID'),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='文档 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='分段内容'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字符/词项数量'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='估算 token 数量'),
    sa.Column('position', sa.Integer(), nullable=False, comment='文档内顺序'),
    sa.Column('keywords', sa.JSON(), nullable=False, comment='关键词'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='检索命中次数'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_segments_document_id'), 'knowledge_segments', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_segments_knowledge_base_id'), 'knowledge_segments', ['knowledge_base_id'], unique=False)
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.BigInteger()),
        sa.column('code', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()))
    role_permissions = sa.table(
        'role_permissions',
        sa.column('role_id', sa.BigInteger()),
        sa.column('permission_id', sa.BigInteger()),
    )
    catalog = (
        ('knowledge_read', '查看知识库', '查看知识库、文档和分段'),
        ('knowledge_create', '创建知识库', '创建知识库配置'),
        ('knowledge_update', '更新知识库', '修改知识库和分段配置'),
        ('knowledge_delete', '删除知识库', '删除知识库及其文件'),
        ('knowledge_document_manage', '管理知识库文档', '上传、重试和删除文档'),
        ('knowledge_segment_update', '更新知识库分段', '编辑文档分段内容'),
        ('knowledge_retrieve', '测试知识检索', '执行知识库本地检索测试'),
    )
    connection = op.get_bind()
    existing_codes = set(connection.execute(sa.select(permissions.c.code)).scalars())
    missing = [
        {'code': code, 'name': name, 'description': description}
        for code, name, description in catalog
        if code not in existing_codes
    ]
    if missing:
        op.bulk_insert(permissions, missing)
    admin_role_id = connection.execute(
        sa.select(roles.c.id).where(roles.c.code == 'admin')
    ).scalar_one_or_none()
    if admin_role_id is not None:
        codes = [code for code, _, _ in catalog]
        permission_ids = list(connection.execute(
            sa.select(permissions.c.id).where(permissions.c.code.in_(codes))
        ).scalars())
        existing_assignments = set(connection.execute(
            sa.select(role_permissions.c.permission_id).where(role_permissions.c.role_id == admin_role_id)
        ).scalars())
        assignments = [
            {'role_id': admin_role_id, 'permission_id': permission_id}
            for permission_id in permission_ids
            if permission_id not in existing_assignments
        ]
        if assignments:
            op.bulk_insert(role_permissions, assignments)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_segments_knowledge_base_id'), table_name='knowledge_segments')
    op.drop_index(op.f('ix_knowledge_segments_document_id'), table_name='knowledge_segments')
    op.drop_table('knowledge_segments')
    op.drop_index(op.f('ix_knowledge_documents_uploaded_by_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_file_name'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_bases_status'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_created_by_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    permission_codes = (
        'knowledge_read', 'knowledge_create', 'knowledge_update', 'knowledge_delete',
        'knowledge_document_manage', 'knowledge_segment_update', 'knowledge_retrieve',
    )
    op.execute(sa.text('DELETE FROM permissions WHERE code IN :codes').bindparams(
        sa.bindparam('codes', expanding=True, value=permission_codes)
    ))
    # ### end Alembic commands ###
