"""修改用户模型-增加最后登录时间

Revision ID: cd0970644d92
Revises: d8a8fe4dd2fa
Create Date: 2026-07-17 18:15:04.858347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0970644d92'
down_revision: Union[str, Sequence[str], None] = 'd8a8fe4dd2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a valid value when this non-nullable column is added.
    op.add_column(
        'users',
        sa.Column(
            'last_login',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP'),
            comment='最后登录时间',
        ),
    )
    op.alter_column(
        'users',
        'last_login',
        existing_type=sa.DateTime(),
        nullable=False,
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
