"""tool_management

Revision ID: eb155c4d538b
Revises: c6e99bac6d31
Create Date: 2026-07-19 19:49:41.588471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb155c4d538b'
down_revision: Union[str, Sequence[str], None] = 'c6e99bac6d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('name', sa.String(length=150), nullable=False, comment='工具名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='工具描述'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='工具类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='工具状态'),
    sa.Column('config_encrypted', sa.Text(), nullable=True, comment='加密后的工具配置'),
    sa.Column('function_definition', sa.JSON(), nullable=True, comment='函数定义'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近 7 日测试/调用次数'),
    sa.Column('success_rate', sa.Numeric(precision=6, scale=2), nullable=False, comment='近 7 日成功率'),
    sa.Column('avg_latency', sa.Numeric(precision=12, scale=2), nullable=False, comment='近 7 日平均延迟'),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True, comment='创建人 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_created_by_id'), 'tools', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_index(op.f('ix_tools_status'), 'tools', ['status'], unique=False)
    op.create_index(op.f('ix_tools_type'), 'tools', ['type'], unique=False)
    op.create_table('tool_executions',
    sa.Column('tool_id', sa.BigInteger(), nullable=False, comment='工具 ID'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='延迟毫秒'),
    sa.Column('is_test', sa.Boolean(), nullable=False, comment='是否测试调用'),
    sa.Column('error', sa.String(length=1000), nullable=True, comment='错误摘要'),
    sa.Column('executed_at', sa.DateTime(), nullable=False, comment='执行时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_executed_at'), 'tool_executions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_tool_executions_is_test'), 'tool_executions', ['is_test'], unique=False)
    op.create_index(op.f('ix_tool_executions_success'), 'tool_executions', ['success'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_id'), 'tool_executions', ['tool_id'], unique=False)
    permissions = sa.table(
        'permissions',
        sa.column('id', sa.BigInteger()),
        sa.column('code', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    roles = sa.table('roles', sa.column('id', sa.BigInteger()), sa.column('code', sa.String()))
    role_permissions = sa.table(
        'role_permissions',
        sa.column('role_id', sa.BigInteger()),
        sa.column('permission_id', sa.BigInteger()),
    )
    catalog = (
        ('tool_read', '查看工具', '查看工具配置和指标'),
        ('tool_create', '创建工具', '登记工具配置'),
        ('tool_update', '更新工具', '修改工具配置'),
        ('tool_delete', '删除工具', '删除工具及其测试记录'),
        ('tool_enable', '启停工具', '启用或停用工具'),
        ('tool_test', '测试工具', '验证工具配置或测试 HTTP 工具'),
    )
    connection = op.get_bind()
    existing_codes = set(connection.execute(sa.select(permissions.c.code)).scalars())
    missing = [
        {'code': code, 'name': name, 'description': description}
        for code, name, description in catalog
        if code not in existing_codes
    ]
    if missing:
        op.bulk_insert(permissions, missing)
    admin_role_id = connection.execute(
        sa.select(roles.c.id).where(roles.c.code == 'admin')
    ).scalar_one_or_none()
    if admin_role_id is not None:
        codes = [code for code, _, _ in catalog]
        permission_ids = list(connection.execute(
            sa.select(permissions.c.id).where(permissions.c.code.in_(codes))
        ).scalars())
        existing_assignments = set(connection.execute(
            sa.select(role_permissions.c.permission_id).where(role_permissions.c.role_id == admin_role_id)
        ).scalars())
        assignments = [
            {'role_id': admin_role_id, 'permission_id': permission_id}
            for permission_id in permission_ids
            if permission_id not in existing_assignments
        ]
        if assignments:
            op.bulk_insert(role_permissions, assignments)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_tool_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_success'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_is_test'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_executed_at'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_tools_type'), table_name='tools')
    op.drop_index(op.f('ix_tools_status'), table_name='tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_created_by_id'), table_name='tools')
    op.drop_table('tools')
    permission_codes = (
        'tool_read', 'tool_create', 'tool_update', 'tool_delete', 'tool_enable', 'tool_test',
    )
    op.execute(sa.text('DELETE FROM permissions WHERE code IN :codes').bindparams(
        sa.bindparam('codes', expanding=True, value=permission_codes)
    ))
    # ### end Alembic commands ###
